### ISSUE TITLE
window right boundary time larger than audio file max time

### ISSUE THREAD

**Issue by msonderegger** [mlml/autovot#56]
It can happen that the right edge of the processing window is larger than the length of the audio file, e.g. if the stop is in the last word in the file and there's no silence afterwards.  (This happens in dru59-day53-Rex-0350 in the BB data.)  In theory the same could happen at the left edge.  Resulting error looks like:

```
wpa151023:vcd_training morgan$ auto_vot_train.py --vot_tier Corrected --vot_mark vot bbVoicedTrainingWavs.txt bbVoicedTrainingTgs.txt bbVoiced.classifier
16:25:55.369 [VotFrontEnd2] INFO: Processing 250 instances.
16:26:20.240 [VotFrontEnd2] ERROR: Word end (71.027) is greater than the length of /Users/morgan/bigbro/drUncut/clips/dru59-day53-Rex-0350_16kHz.wav
16:26:20.255 [utilities.py] ERROR: Either the feature file and the label file are not the same length of label file missing a header
```

can deal with this by setting --window_max to a lower value than the default (800 msec), but instead we should probably just decrease the window max location for that instance, and throw a warning?

**Comment by Ayushi113** [comment]
Hi..
I've had a similar issue with the latest version of AutoVOT, on Ubuntu 16.04, with Python 3.7.6. I'm trying the positive VOT classifier, with <--min_vot_length 15> and <--max_vot_length> as default. 
I've double checked that my List.of.Wavfiles and List.of.TextGrids is synchronized, and the environment is set as /home/ayushi/Tools/autovot/autovot/bin. 
Could this be a Python 3.7 issue?
