### ISSUE TITLE
IndexError When Decoding Voiceless VOT

### ISSUE THREAD

**Issue by ziweizh** [mlml/autovot#76]
I was following the instruction for training and decoding for some Spanish sentence data. I ran it successfully with decoding voiced VOT. However, it threw me this "list index out of range" error when trying to decode voiceless VOT instances.

> Traceback (most recent call last):
>   File "/Users/ziweizh/autovot/autovot/bin/auto_vot_decode.py", line 235, in <module>
>     auto_vot_tier.append(Interval(textgrid.xmin(), xmin_preds[0], ''))
> IndexError: list index out of range

**Comment by jkeshet** [comment]
I cannot reproduce the error. Can you please upload (or send me by email) the command line you used with a single waveform and annotation so I could debug it?
