### ISSUE TITLE
python dependencies, info in readme

### ISSUE THREAD

**Issue by NoahRichardNelson** [mlml/autovot#87]
Hello, and thank you for AutoVOT!

I noticed a few module dependencies that I had to download to get the training portion of the tutorial to work (i.e., to run auto_vot_train.py). Specifically, using Python 3.6.5 on Mac OS X (10.11.6) I had to install the future and textgrid modules (note, link to the repo for textgrid.py in the readme appears to be broken). It looks like it would have been a different set of modules that I was missing if I were using Python 2. Perhaps it would be beneficial to make note of these, and how to install them, into the readme for users who may be less familiar with Python.

**Comment by MichaelGoodale** [comment]
Thanks Noah! A bit of an oversight on our part not to include any detail about prerequisites. I've added a requirements.txt to the base directory as well as updated the README.md to hopefully be a little clearer about that.
