### ISSUE TITLE
"pip -r" in README

### ISSUE THREAD

**Issue by mfaytak** [mlml/autovot#92]
Hi all -

Nice software, which I am currently trying to get up and running. Using Ubuntu 16.04 Xenial. `pip -r requirements.txt` is (so far as I can tell) not a valid command since there isn't an `-r` option for `pip`. This was probably meant to be `pip install -r requirements.txt`. 

Thanks!

**Comment by thealk** [comment]
Yes - that's right, thanks for the notice. Fixed now!
